lib/parrot/django_apps/main_site/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.core.urlresolvers import reverse

from parrot.django_apps.main_site.tokens import PasswordResetTokenGenerator
from parrot.django_apps.main_site.forms  import PasswordResetForm
from parrot.django_apps.main_site.views  import SignInForm

password_reset_token_generator = PasswordResetTokenGenerator()

auth_urlpatterns = patterns('django.contrib.auth.views',                            
    url(r'^logout/$', 'logout', {'template_name': 'main_site/logged_out.html', 'next_page': '/'}, name='logout'),
    #url(r'^logout_then_login/$', 'logout_then_login'),
    #url(r'^passwordchange/$', 'password_change', 
    #    {'template_name': 'main_site/password_change.html',
    #     'post_change_redirect': '/'}),
    url(r'^passwordreset/$', 'password_reset', 
        {'is_admin_site': False,
         'template_name': 'main_site/password_reset.html',
         'email_template_name': 'email/password_reset.html',
         'token_generator': password_reset_token_generator,
         'password_reset_form': PasswordResetForm,
     }, 'passwordreset'),
    url(r'^passwordresetdone/$', 'password_reset_done', 
        {'template_name': 'main_site/password_reset_done.html',
         'extra_context': {'no_reply_address': 'noreply@chatoperated.com'},
     }),
    url(r'^passwordresetconfirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
        'password_reset_confirm', 
        {'template_name': 'main_site/password_reset_confirm.html',
         'post_reset_redirect': '/login/',
         'token_generator': password_reset_token_generator},
        name='password-reset-confirm'))

site_urlpatterns = patterns(
    'parrot.django_apps.main_site.views',
    url(r"^$", "home", name="home"),
    url(r"^robots.txt$", "robots", name="robots"),
    url(r"^chatoperated/$", "chat_operated", name="chat_operated"),        
    url(r"^terms/$",  "terms",  name="terms"),
    url(r"^signup/$", "signup", name="signup"),    
    url(r"^signupconfirm/$", "signup_confirm", name="signup-confirm"),    
    url(r'^login/$',  'login',  {'template_name': 'main_site/login.html', 'authentication_form': SignInForm}, name='login'),
    url(r"^member/$", "member_home", name="member-home"),
    url(r"^member/verify/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$", "member_verify", name="member-verify"),
    url(r"^api/v1/user/$", "user_view", name="user"),
    url(r"^api/v1/user/(?:(?P<user_id>\d+)/)$", "user_view", name="user"),
    url(r"^api/v1/user-stats/$", "user_stats", name="user-stats"),    
    url(r"^api/v1/user-notification/(?:(?P<user_notification_id>\d+)/)?$", "user_notification", name="user-notification"),
    url(r"^api/v1/phrase-request/$", "phrase_request", name="phrase-request"),
    url(r"^api/v1/phrase-response/$", "phrase_response", name="phrase-response"),
    url(r"^api/v1/phrase-request/(?P<phrase_request_id>\d+)/$",
        "phrase_request", name="phrase-request"),
    url(r"^api/v1/phrase-response/(?P<phrase_response_id>\d+)/$",
        "phrase_response", name="phrase-response"),
    url(r"^api/v1/phrase-response/(?P<phrase_response_id>\d+)/clip/$", "phrase_response_clip", name="phrase-response-clip"),    
    url(r"^api/v1/invite/$", 'invite', name="invite"),    
    )

urlpatterns = patterns('',
    url(r'^', include(site_urlpatterns)),
    url(r'^', include(auth_urlpatterns))
)

if settings.DEBUG:
    urlpatterns += patterns(
        'parrot.django_apps.main_site.views',
        url(r"^test/$", "test", name="test"),
    )

handler500 = 'parrot.django_apps.main_site.views.handler500'

lib/parrot/django_apps/main_site/forms.py
# -*- coding: utf-8 -*-

import re
import datetime

from django import forms
from django.forms.util import flatatt
from django.template import loader
from django.utils.encoding import smart_str
from django.utils.http import int_to_base36
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext, ugettext_lazy as _, get_language
from django.core.urlresolvers import reverse
from django.core.mail import send_mail
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.hashers import UNUSABLE_PASSWORD, is_password_usable, get_hasher
from django.contrib.sites.models import get_current_site
from django.conf import settings

from parrot.django_apps.main_site.models import *
from parrot.django_apps.main_site.emails import SignUpEmail, PasswordResetEmail, get_site_vars
from parrot.django_apps.main_site.tokens import default_token_generator
from parrot.utils.language import *
from parrot import SITE_FULL_ADDRESS

MIN_AGE = 13

SEPARATOR_CHOICE = None  # FIXME/DEFINE ME as: "<option disabled>──────────</option>"
LANGUAGE_CODE_CHOICES = sorted(LANGUAGES_NATIVE_NAMES.items(), key=lambda (a, b): b)

def add_years(dt, years):
    return dt.replace(year=dt.year+years)

def subtract_years(dt, years):
    return add_years(dt, -years)

def form_labels_to_placeholders(form, exclude=()):
    for k, f in form.fields.iteritems():
        if k in exclude:
            continue
        if isinstance(f.widget, (forms.TextInput, forms.PasswordInput)):
            f.widget.attrs['placeholder'] = f.label

class UserCreationForm(forms.ModelForm):
    """
    A form that creates a user, with no privileges, from the given username and
    password.
    """
    error_messages = {
        'duplicate_username': _("A user with that username already exists. Did you mean to sign in?"),  # <a href='{login_url}'>sign in</a>
    }
    username = forms.EmailField(label=_("Email"), max_length=75)
    password = forms.CharField(label=_("Password"),
        widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("username",)

    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)

    def clean_username(self):
        # Since User.username is unique, this check is redundant,
        # but it sets a nicer error message than the ORM. See #13147.
        username = self.cleaned_data["username"].lower()
        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username
        error_message = self.error_messages['duplicate_username'].format(login_url=reverse('login'))
        raise forms.ValidationError(error_message)

    def save(self, request=None, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.email = user.username
        user.set_password(self.cleaned_data["password"])
        
        if commit:
            user.save()
        
        SignUpEmail().create_mail(user.email)

        return user

class UserProfileForm(forms.Form):
    """
    A form to update a user profile.
    """
    nickname = forms.CharField(label=_('Nickname'), max_length=30, required=False)
    age = forms.IntegerField(label=_('Age'), widget=forms.Select, min_value=0, max_value=100,
                             required=False)
    gender = forms.ChoiceField(label=_('Gender'),
                               choices=(('m', 'Male'), ('f', 'Female')),
                               required=False)
    country = forms.ChoiceField(label=_('Country'), required=False)
    language = forms.ChoiceField(label=_('Language'), choices=LANGUAGE_CODE_CHOICES, required=False)
    interest_language = forms.ChoiceField(label=_('Language'), choices=LANGUAGE_CODE_CHOICES,
                                          required=False)    
    terms_accepted = forms.BooleanField(label=_('Terms accepted'), required=False)

    def __init__(self, user, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)

        country_field = self.fields['country']
        country_field.choices = [('', 'Country')]
        country_field.choices.extend(sorted([(country['code'], country['name']) for country in Country.objects.all().values('code', 'name')], key=lambda x: x[1]))

        age_field = self.fields['age']
        age_choices = [(x, x) for x in xrange(MIN_AGE, age_field.max_value)]
        age_choices.insert(0, (0, _('Under {min_age_in_years}').format(min_age_in_years=MIN_AGE)))
        age_field.widget.choices = age_choices
        
        self.fields['terms_accepted'].label = \
            mark_safe(_('I have read and agree to the <a href="{terms_url}">Terms of Service</a>.').format(terms_url=reverse('terms')))

        self._user = user
        
        user_profile = user.get_profile()
        if not user_profile.terms_accepted:
            # Set initial value for "native language" our best guess
            # LCID => Language code
            language_code = user_profile.language_code
            if language_code is None:
                language_code, country_code = \
                    [x.lower() for x in get_language().split('-')]
            self.fields['language'].initial = language_code
            self.fields['nickname'].widget.attrs['placeholder'] = _('Anonymous')
        else:
            self.fields['language'].initial = user_profile.language_code
            self.fields['interest_language'].initial = user_profile.interest_language_code
            self.fields['nickname'].initial = user_profile.nickname            
            self.fields['age'].initial = user_profile.age
            self.fields['gender'].initial = user_profile.gender
            self.fields['country'].initial = user_profile.country.code
            self.fields['terms_accepted'].initial = user_profile.terms_accepted

        form_labels_to_placeholders(self, exclude=('nickname',))

    def clean_age(self):        
        age = self.cleaned_data["age"]
        if age is not None and age < MIN_AGE:
            raise forms.ValidationError(_('You must be at least {min_age_in_years} years old to participate.'.format(min_age_in_years=MIN_AGE)))
        return age

    def save(self, commit=True):
        user_profile = self._user.get_profile()

        if self.cleaned_data['age']:
            user_profile.birth_date = subtract_years(datetime.date.today(), 
                                                     self.cleaned_data["age"])

        if self.cleaned_data['country']:
            user_profile.country = Country.objects.get(code=self.cleaned_data["country"])

        if self.cleaned_data["terms_accepted"]:
            terms = TermsOfService.objects.order_by('-effective_date')[0]
            user_profile.terms_accepted = terms.effective_date
        
        if self.cleaned_data["nickname"]:
            user_profile.nickname = self.cleaned_data["nickname"]

        if self.cleaned_data["language"]:
            user_profile.language_code = self.cleaned_data["language"]
            
        if self.cleaned_data["interest_language"]:
            user_profile.interest_language_code = self.cleaned_data["interest_language"]
            
        if commit:
            user_profile.save()

        return user_profile

class UserProfileCreationForm(UserProfileForm):
    def __init__(self, user, *args, **kwargs):
        super(UserProfileCreationForm, self).__init__(user, *args, **kwargs)
        for k, f in self.fields.iteritems():
            if k in ('terms_accepted', 'country', 'age'):
                f.required = True

class SignInForm(AuthenticationForm):
    def clean_username(self):
        return self.cleaned_data["username"].lower()

    def __init__(self, *args, **kwargs):
        super(SignInForm, self).__init__(*args, **kwargs)

        self.fields['username'].label = _('Email address')
        self.fields['password'].label = _('Password')

        form_labels_to_placeholders(self)        

class SignUpForm(UserCreationForm):
    language = forms.ChoiceField(label=_('Language'), choices=LANGUAGE_CODE_CHOICES, required=False)
    interest_language = forms.ChoiceField(label=_('Language'), choices=LANGUAGE_CODE_CHOICES, required=False)

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)

        language_code, country_code = [x.lower() for x in get_language().split('-')]
        self.fields['language'].initial = language_code
        self.fields['username'].label = _('Email address')
        self.fields['password'].label = _('New password')

        form_labels_to_placeholders(self)                

    def save(self, request=None):
        user = super(SignUpForm, self).save(request=request, commit=True)
        user_profile = user.get_profile()
        user_profile.language_code = self.cleaned_data["language"]        
        user_profile.interest_language_code = self.cleaned_data["interest_language"]
        user_profile.save()
        return user        

class PasswordResetForm(forms.Form):
    error_messages = {
        'unknown': _("That email address doesn't have an associated "
                     "user account. Are you sure you've registered?"),
        'unusable': _("The user account associated with this email "
                      "address cannot reset the password."),
    }
    email = forms.EmailField(label=_("Email address"), max_length=75)

    def clean_email(self):
        """
        Validates that an active user exists with the given email address.
        """
        email = self.cleaned_data["email"]
        self.users_cache = User.objects.filter(username__iexact=email,
                                               is_active=True)
        if not len(self.users_cache):
            raise forms.ValidationError(self.error_messages['unknown'])
        if any((user.password == UNUSABLE_PASSWORD)

lib/parrot/django_apps/main_site/templates/main_site/base.html
{% load less %}
{% load staticfiles %}
{% load url from future %}
{% load i18n %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
<title>{% block title %}{{ site_name }}{% endblock %}</title>
<meta charset="utf-8">
<meta name="description" content="{% trans 'Listen to learn a language, dialect or accent. Record yourself to help others.' %}">
<meta name="author" content="{{ site_name }}">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="shortcut icon" href="{{ STATIC_URL }}img/favicon.png">
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}{% if debug %}{% less "less/base.less" %}{% else %}css/base.css{% endif %}" />
{% block extrastyle %}{% endblock %}
<!--[if lte IE 7]><link rel="stylesheet" type="text/css" href="{% block stylesheet_ie %}{% static "css/ie.css" %}{% endblock %}" /><![endif]-->
{% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% block stylesheet_rtl %}{% static "css/rtl.css" %}{% endblock %}" />{% endif %}
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-67802819-1', 'auto');
  ga('send', 'pageview');
</script>
<script>
window.__media_prefix__="{% filter escapejs %}{% static "" %}{% endfilter %}";
</script>
{% block extrahead %}{% endblock %}
{% block robots %}<meta name="robots" content="noindex,nofollow" />{% endblock %}
</head>
<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}">
  {% block header %}
  <div class="container-header">
    {% if not is_popup %}
    <div id="flairbar"></div>
    {% endif %}    
    <div class="container-inner-header">
      <div id="header" class="header">
        <div class="header-item">
          <div class="brand-wrapper">
            <a href="{% url 'home' %}">{#<img src="{{ STATIC_URL }}img/text_logo.png" alt="{{ site_name }}" width="207" height="30"/>#}<h1>{{ site_name }}</h1></a>
          </div>
        </div>
        <div class="header-item">
          <div class="navlinks">
            {% if user.is_active %}
            {% if user_profile %}
            <div class="user-profile">
              <div class="user-profile-item">{{ user_profile.nickname|default:"Anonymous" }}</div>
              {% if user_profile.gender %}<div class="user-profile-item">{{ user_profile.gender }}</div>{% endif %}
              <div class="user-profile-item">{% trans 'around' %} {{ user_profile.age }}</div>
              <div class="user-profile-item">{{ user_profile.country_name }}</div>
            </div>
            {% endif %}
            <a id="signout_link" href="{% url 'logout' %}">{% trans 'sign out' %}</a>
            {% else %}
            <a id="signin_link"  href="{% url 'login' %}">{% trans 'sign in' %}</a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endblock %}
  {% if not is_popup %}<div class="container-body">{% endif %}
  {% block body %}{% endblock %}
  {% if not is_popup %}</div>{% endif %}
  {% block footer %}
  <div class="container-footer">
    <div class="container-inner-footer">
      <div id="footer" class="footer">
        <div class="credit">{% trans "Copyright" %} &copy; {% now "Y" %} {{ site_name }}. {% trans "All rights reserved." %}</div>
        <ul class="footer-link-list">
          <li><a href="{% url 'terms' %}">{% trans 'Terms of Service' %}</a></li>
          <li><a href="mailto:help@{{ mail_domain }}">{% trans 'Feedback' %}</a></li>
        </ul>
      </div>
    </div>
  </div>
  {% endblock %}

  {% block extrabody %}
  <!-- Bootstrap core JavaScript
       ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <script src="{{ STATIC_URL }}js/jquery.min.js"></script>
  <script src="{{ STATIC_URL }}js/jquery.cookie.js"></script>
  <script type="text/javascript">
    var csrftoken = $.cookie('csrftoken'), authtoken = "{{ auth_token }}";
    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    function sameOrigin(url) {
        // test that a given url is a same-origin URL
        // url could be relative or scheme relative or absolute
        var host = document.location.host; // host + port
        var protocol = document.location.protocol;
        var sr_origin = '//' + host;
        var origin = protocol + sr_origin;
        // Allow absolute or scheme relative URLs to same origin
        return (url == origin || url.slice(0, origin.length + 1) == origin + '/') ||
            (url == sr_origin || url.slice(0, sr_origin.length + 1) == sr_origin + '/') ||
            // or any other URL that isn't scheme relative or absolute i.e relative.
            !(/^(\/\/|http:|https:).*/.test(url));
    }
    $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && sameOrigin(settings.url)) {
                // Send the token to same-origin, relative URLs only.
                // Send the token only if the method warrants CSRF protection
                // Using the CSRFToken value acquired earlier
                xhr.setRequestHeader("X-CSRFToken", csrftoken);                
            }
            xhr.setRequestHeader("X-AuthToken", authtoken);
        }        
    });

    $(function() {
        var input = document.createElement("input");
        if (('placeholder' in input)==false) { 
            $('[placeholder]').focus(function() {
                var i = $(this);
                if(i.val() == i.attr('placeholder')) {
                    i.val('').removeClass('placeholder');
                    if(i.hasClass('password')) {
                        i.removeClass('password');
                        this.type='password';
                    }           
                }
            }).blur(function() {
                var i = $(this);    
                if(i.val() == '' || i.val() == i.attr('placeholder')) {
                    if(this.type=='password') {
                        i.addClass('password');
                        this.type='text';
                    }
                    i.addClass('placeholder').val(i.attr('placeholder'));
                }
            }).blur().parents('form').submit(function() {
                $(this).find('[placeholder]').each(function() {
                    var i = $(this);
                    if(i.val() == i.attr('placeholder'))
                        i.val('');
                })
            });
        }
    });
  </script>
  <script src="{{ STATIC_URL }}bootstrap/js/bootstrap.min.js"></script>
  {% endblock %}
</body>
</html>

lib/parrot/django_apps/main_site/templates/main_site/chat_operated.html
{% extends "main_site/base.html" %}
{% load i18n %}{% load url from future %}

{% block body %}
<div class="x-container-narrow">
  <h2>{% trans "Goodbye, Chat-Operated!" %}</h2>
  <p>{% blocktrans %}The Chat-Operated site and all services have been suspended indefinitely. Spoken phrases are the future.{% endblocktrans %}</p>
</div>
{% endblock %}

lib/parrot/django_apps/main_site/templates/main_site/home.html
{% extends "main_site/base.html" %}
{% load url from future %}
{% load i18n %}
{% load css %}

{% block title %}{{ block.super }}: {% trans 'Phrases spoken by native speakers' %}{% endblock %}

{# {% block extrahead %}<meta name="google-site-verification" content="CgPUKT3YIBJtyMPHKbZgPUoEuoebwodFimYeBW9iBpU" /><meta name="msvalidate.01" content="BFB02D7F1B1D824A0F1C0F05CB271813" />{% endblock %} #}

{% block robots %}<meta name="robots" content="noarchive" />{% endblock %}

{% block header %}{% endblock %}

{% block body %}
<div class="container-home">
  <div class="container-signup">
    <div class="promo">
      <h1>{{ site_name }}</h1>
      <h2>{% trans 'Phrases spoken by native speakers' %}</h2>
      <p>{% trans 'Listen to learn a language, dialect or accent.' %}<br/>{% trans 'Record yourself to help others.' %}</p>
      <div class="signin-link"><a href="{% url 'login' %}">{% trans 'sign in' %}</a></div>
    </div>
    <div class="signup-box">
      <form id="signup-form" class="form-signup form" method="POST" action="{% url 'user' %}">
        {% csrf_token %}
        <h3>Join the community!</h3>                    
        <fieldset>
          {{ signup_form.username|wrap:"class=field" }}
          {{ signup_form.password|wrap:"class=field" }}
          <label for="id_language">
            {% trans 'My native language is' %}
            {{ signup_form.language|wrap:"class=field" }}
          </label>         
          <label for="id_interest_language">
            {% trans 'I am learning' %}
            {{ signup_form.interest_language|wrap:"class=field" }}
          </label>
          <button type="submit" id="signup-submit" class="submit">{% trans 'Sign up for ' %}{{ site_name }}</button>        
        </fieldset>
      </form>
    </div>
  </div>  
</div>
{% endblock %}

{% block extrabody %}{{ block.super }}
<script type="text/javascript">
    var frm = $('#signup-form');
    $('.field, .form').focusin(function() {
        $(this).removeClass('show-form-error');
    });
    var hideFormErrors = function(frm) {
        $('.show-form-error', (frm||this).parent).removeClass('show-form-error');
    };
    frm.submit(function() {
        var setErrorTimeout = function(t) {
            if (this.errorTimeout) {
                clearTimeout(this.errorTimeout);
            }
            this.errorTimeout = t;
        }.bind(this);
        
        $.ajax({
            type: frm.attr('method'),
            url:  frm.attr('action'),
            data: frm.serialize(),
            success: function (resp) {
                window.location.href = "{% url 'signup-confirm' %}";
            }.bind(this),
            error: function(resp) {                
                if (resp.status == 400) {
                    var errors = $.parseJSON(resp.responseText);
                    $('.field', this).each(function(e) {
                        var text = errors[$(this).children()[0].name];
                        if (text !== undefined) {
                            $(this).addClass('show-form-error').attr('data-text', text);
                        }
                    });
                } else {
                    $(this).addClass('show-form-error').attr('data-text', "{% trans 'Due to technical difficulties, we were unable to send your invitation. Please try again later.' %}");
                }
                setErrorTimeout(setTimeout(hideFormErrors.bind(this), 5000));
            }.bind(this)
        });
        return false;
    });
</script>
{% endblock %}

lib/parrot/django_apps/main_site/templates/main_site/logged_out.html
{# {% extends "base.html" %} #}

{% block content %}
<h1>Logged out.</h1>
{% endblock %}

lib/parrot/django_apps/main_site/templates/main_site/login.html
{% extends "main_site/base.html" %}
{% load i18n %}{% load url from future %}
{% load compressed %}
{% load css %}

{% block body %}
<div class="container-signin">
  <div class="signin-box">
    <h2>{% trans "Sign in" %}</h2>
    <form id="signin-form" class="form-signin form" method="post" action="{% url 'parrot.django_apps.main_site.views.login' %}">
      {% csrf_token %}
      <fieldset>{% for f in form %}{{ f|wrap:"class=field" }}{% endfor %}</fieldset>
      <div class="container-msg">
      {% if form.errors %}
      <!--<p class="msg msg-error">{% trans "Your username and password didn't match. Please try again." %}</p>-->
      {% endif %}
      </div>
      <button type="submit" value="login">{% trans "Sign in" %}</button>
      <a id="forgot-password" href="{% url 'django.contrib.auth.views.password_reset' %}">{% trans "Forgot your password?" %}</a>
      <input type="hidden" name="next" value="{{ next }}" />
    </form>
  </div>
</div>
{% endblock %}

{% block extrabody %}{{ block.super }}
{% compressed_js 'home' %}    
<script type="text/javascript">
  var util = Util();
  util.addFormErrors(util.initializeForm($('#signin-form')),
  { {% for f, e in form.errors.items %}{{ f }}: "{{ e.0 }}", {% endfor %} });
</script>
{% endblock %}

lib/parrot/django_apps/main_site/templates/main_site/password_change.html
<div>
  <h1>Password change.</h1>
</div>

lib/parrot/django_apps/main_site/templates/main_site/password_change_done.html
<div>
  <h1>Password change done.</h1>
</div>

lib/parrot/django_apps/main_site/templates/main_site/password_reset.html
{% extends "main_site/base.html" %}
{% load i18n %}{% load url from future %}

{% block body %}
<div class="container-password-reset">
  <div class="password-reset-box">
    <h2>{% trans "Forgot your password?" %}</h2>
<p>{% blocktrans %}We'll send you an email with a link to reset your password.{% endblocktrans %}</p>
    <form id="password-reset-form" class="form-signin form" method="post" action=".">
      {% csrf_token %}
      <fieldset>
        <div class="field">
          <input id="id_{{ form.email.name }}" type="text" placeholder="{{ form.email.label }}" name="{{ form.email.name }}" maxlength="30">
        </div>
      </fieldset>
      {% if form.errors %}
      <div class="form-error">{% trans "There was an error requesting the password reset. Are you sure this is the email address associated with your account?" %}</div>
      {% endif %}
      <button type="submit" value="resetpassword">{% trans "Send reset email" %}</button>
    </form>
  </div>
</div>
{% endblock %}

lib/parrot/django_apps/main_site/templates/main_site/signup.html
{% extends "main_site/base.html" %}
{% load i18n %}{% load url from future %}
{% load compressed %}
{% load css %}

{% block title %}{{ block.super }}{% endblock %}

{% block body %}
<div class="container-complete-signup">
  <div class="complete-signup-box">
    <h2>{% trans "You've almost finished signing up!" %}</h2>
    <form id="complete-signup-form" class="form-complete-signup form" method="PUT" action="{% url 'user' %}">
      {% csrf_token %}
      <fieldset>
        <div class="field optional-field">            
          <label for="id_nickname">
            {{ signup_form.nickname.label }}
          </label>
          {{ signup_form.nickname }}          
        </div>
        <div class="field">                    
          <label for="id_age">
            {{ signup_form.age.label }}
          </label>
          {{ signup_form.age }}          
        </div>
        <div class="field">                            
          <label for="id_gender">
            {{ signup_form.gender.label }}
          </label>
          {{ signup_form.gender }}          
        </div>
        <div class="field">
          <label for="id_country">
            {% trans 'Hometown' %}
          </label>
          {{ signup_form.country }}{{ signup_form.state }}{{ signup_form.city }}
        </div>
        <div class="field">
          <label>
            {{ signup_form.terms_accepted.label }}
          </label>
          {{ signup_form.terms_accepted }}                    
        </div>
      </fieldset>
      <button type="submit" class="submit">{% trans "Sign up" %}</button>
    </form>
  </div>
</div>
{% endblock %}

{% block extrabody %}{{ block.super }}
{% compressed_js 'home' %}    
<script type="text/javascript">
    {
        var util = Util();
        var frm  = util.initializeAjaxForm(
            $('#complete-signup-form'),
            {success: function() {
                window.location.href = "{% url 'member-home' %}"; }
            }, 
            "{% blocktrans %}Due to technical difficulties, we're unable to update your profile. Please try again later.{% endblocktrans %}");
    }
</script>
{% endblock %}